DATA_COLUMNS = [
    'PARAMETER_TYPE', 'TREATMENTS', 'TARGET', 'PVALUE', 'ADJUSTED_PVALUE', 
    'ESTIMATE', 'LWB', 'UPB', 'STD', 'CASE', 'CONTROL', 'CONFOUNDERS', 
    'COVARIATES', 'INITIAL_ESTIMATE', 'LOG']

MT_ADJUSTEMENT_METHODS = ["Trait based Benjamini Hochberg", "None"]